// @ts-expect-error generated by the OpenNext Cloudflare build step
import openNextWorker from './.open-next/worker.js'

import { runMediaCleanupCron } from './src/worker/mediaCleanupCron'

type WorkerEnv = Record<string, unknown>

export default {
  async fetch(request: Request, env: WorkerEnv, ctx: ExecutionContext) {
    return openNextWorker.fetch(request, env, ctx)
  },

  async scheduled(_event: ScheduledEvent, env: WorkerEnv, _ctx: ExecutionContext) {
    try {
      const result = await runMediaCleanupCron(env as { D1: D1Database; R2: R2Bucket })

      console.info(
        `[media-cleanup:cron] scanned=${result.scannedCount} referenced=${result.referencedCount} deleted=${result.deletedIds.length}`,
      )
    } catch (error) {
      console.error(
        `[media-cleanup:cron] failed: ${error instanceof Error ? error.message : 'unknown error'}`,
      )
      throw error
    }
  },
}
